name:                simple-kv
version:             0.1.0.0
github:              "abailly/iut-prog-dist"
license:             BSD3
author:              "Arnaud Bailly"
maintainer:          "arnaud@aleryo.com"
copyright:           "2019 Arnaud Bailly"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/abailly/iut-prog-dist#readme>

default-extensions:
- OverloadedStrings
- DuplicateRecordFields

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- base16-bytestring
- base64-bytestring
- containers
- data-default
- lens
- mtl
- random
- servant
- servant-server
- servant-swagger
- swagger2
- text
- time
- wai
- wai-extra
- warp

library:
  source-dirs:         src
  exposed-modules:
  - KV
  - KV.Server
  - KV.Store
  - KV.Types
  ghc-options:
  - -Wall
  - -Werror
  - -fno-warn-orphans

executables:
  kv:
    main:                kvstore.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-kv

tests:
  kv-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-kv
    - hspec
    - hspec-discover
    - hspec-wai
    - http-types
    - QuickCheck
    - quickcheck-instances
